### ISSUE TITLE
Add survey link to map itself, generally make it more prominent

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/RepairDirectory#88]
Currently it's a link in the Repair Directory page on therestartproject.org - https://therestartproject.org/repairdirectory/

We could have a link in the business popup.  Ideally a popup that appears following clicking through to a business.

**Comment by spt1224** [comment]
I've added a link to the business popups. The link appears automatically after a brief delay. LMK if you'd like any changes to the text or appearance.

And then, once someone actually clicks a business' link... because you're displaying the directory in an iframe on therestartproject.org, it almost seemed reasonable to me to redirect the iframe directly to the survey URL.

We could do a modal instead, but that might mean adding some JS to the parent document on https://therestartproject.org/repairdirectory/

Wanted to get your feedback before I submit a PR.
